/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			colors: {
				'primary-light': '#ece7ea',
				'primary-dark': '#121212',
				'primary-blue': '#3949e3',
				'primary-yellow': '#ffcb25',
				'primary-slate': '#1e293b',
			},
			fontFamily: {
				'roboto-mono': ['Roboto Mono', 'monospace'],
				'open-sans': ['Open Sans', 'sans-serif'],
				'inter': ['Inter', 'sans-serif'],
			},
			fontSize: {
				'font-0': 'var(--font-0)',
				'font-1': 'var(--font-1)',
				'font-2': 'var(--font-2)',
				'font-3': 'var(--font-3)',
				'font-4': 'var(--font-4)',
				'font-5': 'var(--font-5)',
				'font--1': 'var(--font--1)',
				'font--2': 'var(--font--2)',
			},
			animation: {
				'flip-down-0': 'flip-down .5s both',
				'flip-down-1': 'flip-down 1s both;',
				'flip-down-2': 'flip-down 2s both;',
				'flip-down-3': 'flip-down 3s both;',
				'flip-down-4': 'flip-down 4s both;',
				'flip-up-0': 'flip-up .5s both',
				'flip-up-1': 'flip-up 1s both;',
				'flip-up-2': 'flip-up 2s both;',
				'flip-up-3': 'flip-up 3s both;',
				'flip-up-4': 'flip-up 4s both;',
				'fade-left-0': 'fade-left .5s both',
				'fade-left-1': 'fade-left 1s both;',
				'fade-left-2': 'fade-left 2s both;',
				'fade-left-3': 'fade-left 3s both;',
				'fade-left-4': 'fade-left 4s both;',
				'fade-right-0': 'fade-right .5s both',
			},
			spacing: {
        '3xs': 'var(--space-3xs)',
        '2xs': 'var(--space-2xs)',
        'xs': 'var(--space-xs)',
        's': 'var(--space-s)',
        'm': 'var(--space-m)',
        'l': 'var(--space-l)',
        'xl': 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
        '3xs-2xs': 'var(--space-3xs-2xs)',
        '2xs-xs': 'var(--space-2xs-xs)',
        'xs-s': 'var(--space-xs-s)',
        's-m': 'var(--space-s-m)',
        'm-l': 'var(--space-m-l)',
        'l-xl': 'var(--space-l-xl)',
        'xl-2xl': 'var(--space-xl-2xl)',
        '2xl-3xl': 'var(--space-2xl-3xl)',
        's-l': 'var(--space-s-l)',
      },
		},
	},
	plugins: [],
}
